id: P005557
initial_creation_type: ocr
source_metadata:
  id: bdr:W20130
  title: ཁ་བའི་རྣམ་ཤེས།
  author: ''
  volumes:
    ad7a7996a2c341b9967e1de9f17c6ada:
      image_group_id: I1KG15015
      title: ''
      volume_number: 1
      total_pages: 492
      base_file: v001.txt
