id: P005557
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:59:09.397281
source_metadata:
  id: bdr:W20130
  title: ཁ་བའི་རྣམ་ཤེས།
  author: ''
  volumes:
    ad7a7996a2c341b9967e1de9f17c6ada:
      image_group_id: I1KG15015
      title: ''
      volume_number: 1
      total_pages: 492
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
